name: Deploy Properdocs

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/site.yml"
      - "scripts/**"
      - "docs/**"
      - "overrides/**"
      - "properdocs.yml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install Pillow sudachipy sudachidict_core

      - name: Build OGP
        run: |
          python ./scripts/generate_ogp.py
      - name: Install Properdocs
        run: |
          pip install properdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-ruby-plugin

      - name: Deploy documentation
        run: properdocs gh-deploy --force
